#!/bin/bash

# Configuration
PROJECT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# Conditionally use bundled Node if present (Work Laptop specific)
BUNDLED_NODE="$PROJECT_ROOT/../../node-v22/bin"
if [ -d "$BUNDLED_NODE" ]; then
    export PATH="$BUNDLED_NODE:$PATH"
fi
BACKEND_DIR="$PROJECT_ROOT/backend"
DATA_DIR="$PROJECT_ROOT/data"
WEB_DIR="$PROJECT_ROOT/web-ui"
MODE="${BETA6_MODE:-${BETA55_MODE:-prod}}"         # dev|prod (production-safe default)
WEB_PORT="${WEB_PORT:-3002}"
EXPORT_PORT="${EXPORT_PORT:-8503}"
DEFAULT_STREAMLIT_APP="$BACKEND_DIR/app/main.py"
LEGACY_STREAMLIT_APP="$BACKEND_DIR/export_dashboard.py"
STREAMLIT_APP_PATH="${STREAMLIT_APP_PATH:-$DEFAULT_STREAMLIT_APP}"

# Critical: Add Project Root to PYTHONPATH so 'from backend...' imports work
export PYTHONPATH="$PROJECT_ROOT:$PYTHONPATH"
DB_CONTAINER_NAME="${DB_CONTAINER_NAME:-elderlycare_timescaledb}"

sync_web_env() {
    cat > "$WEB_DIR/.env" <<EOF
# Auto-generated by start.sh to keep Web UI and backend on the same DB credentials.
POSTGRES_HOST=$POSTGRES_HOST
POSTGRES_PORT=$POSTGRES_PORT
POSTGRES_USER=$POSTGRES_USER
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=$POSTGRES_DB
EOF
}

set_env_key() {
    local file="$1"
    local key="$2"
    local value="$3"
    if [ ! -f "$file" ]; then
        return
    fi
    if grep -q "^${key}=" "$file"; then
        sed -i.bak "s|^${key}=.*|${key}=${value}|" "$file" && rm -f "${file}.bak"
    else
        printf "%s=%s\n" "$key" "$value" >> "$file"
    fi
}

require_authority_env_contracts() {
    local authority_enabled="${ENABLE_BETA6_AUTHORITY:-true}"
    if ! is_truthy "$authority_enabled"; then
        return 0
    fi

    if [ -z "${RELEASE_GATE_EVIDENCE_PROFILE:-}" ]; then
        echo "❌ RELEASE_GATE_EVIDENCE_PROFILE must be set explicitly when ENABLE_BETA6_AUTHORITY=true."
        echo "   - Set it in $BACKEND_DIR/.env before starting the platform."
        return 1
    fi

    if [ -z "${BETA6_GATE_SIGNING_KEY:-}" ]; then
        echo "❌ BETA6_GATE_SIGNING_KEY must be set explicitly when ENABLE_BETA6_AUTHORITY=true."
        echo "   - Set it in $BACKEND_DIR/.env before starting the platform."
        return 1
    fi

    return 0
}

is_truthy() {
    local raw="$(printf '%s' "${1:-}" | tr '[:upper:]' '[:lower:]')"
    case "$raw" in
        1|true|yes|y|on|enabled) return 0 ;;
        *) return 1 ;;
    esac
}

can_auth_postgres() {
    local pw="$1"
    docker exec -e PGPASSWORD="$pw" "$DB_CONTAINER_NAME" \
        psql -h localhost -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "SELECT 1" >/dev/null 2>&1
}

reconcile_postgres_password() {
    if can_auth_postgres "$POSTGRES_PASSWORD"; then
        return 0
    fi

    for legacy_pw in password elderlycare; do
        if [ "$legacy_pw" != "$POSTGRES_PASSWORD" ] && can_auth_postgres "$legacy_pw"; then
            POSTGRES_PASSWORD="$legacy_pw"
            export POSTGRES_PASSWORD
            set_env_key "$BACKEND_DIR/.env" "POSTGRES_PASSWORD" "$POSTGRES_PASSWORD"
            set_env_key "$BACKEND_DIR/.env" "POSTGRES_HOST" "$POSTGRES_HOST"
            set_env_key "$BACKEND_DIR/.env" "POSTGRES_PORT" "$POSTGRES_PORT"
            set_env_key "$BACKEND_DIR/.env" "POSTGRES_USER" "$POSTGRES_USER"
            set_env_key "$BACKEND_DIR/.env" "POSTGRES_DB" "$POSTGRES_DB"
            sync_web_env
            echo "⚠️  PostgreSQL password mismatch detected. Auto-synchronized env files to existing DB credentials."
            return 0
        fi
    done

    echo "❌ PostgreSQL authentication failed for user '$POSTGRES_USER'."
    echo "   - Checked configured and legacy passwords but none worked."
    echo "   - Update $BACKEND_DIR/.env with the real database credentials."
    return 1
}

# Cleanup function
cleanup() {
    echo ""
    echo "🛑 Stopping all services..."
    kill $PID_WATCHER $PID_EXPORT $PID_WEB 2>/dev/null
    exit 0
}

# Trap SIGINT (Ctrl+C), SIGTERM, SIGHUP (Terminal Close), and EXIT (Clean shutdown)
trap cleanup SIGINT SIGTERM SIGHUP EXIT

echo "--------------------------------------------------"
echo " Elderly Care Platform - Beta_6 (Transformer Prototype)"
echo "--------------------------------------------------"

# 0. Ensure clean start - kill any orphan processes
echo "🧹 Cleaning up any previous instances..."
"$PROJECT_ROOT/stop.sh"

# 1. Environment Check
if [ ! -d "$BACKEND_DIR" ]; then
    echo "Error: Backend directory not found at $BACKEND_DIR"
    exit 1
fi

# 2. Setup Dependencies & Environment
echo "🔧 Setting up backend..."
if [ -f "$BACKEND_DIR/.env.example" ] && [ ! -f "$BACKEND_DIR/.env" ]; then
    cp "$BACKEND_DIR/.env.example" "$BACKEND_DIR/.env"
    echo "   - Created .env file"
fi

# Load backend env and unify PostgreSQL credentials for all services.
if [ -f "$BACKEND_DIR/.env" ]; then
    set -a
    source "$BACKEND_DIR/.env"
    set +a
fi
POSTGRES_HOST="${POSTGRES_HOST:-localhost}"
POSTGRES_PORT="${POSTGRES_PORT:-5432}"
POSTGRES_USER="${POSTGRES_USER:-postgres}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-password}"
POSTGRES_DB="${POSTGRES_DB:-elderlycare}"
ENABLE_BETA6_AUTHORITY="${ENABLE_BETA6_AUTHORITY:-true}"
RELEASE_GATE_EVIDENCE_PROFILE="${RELEASE_GATE_EVIDENCE_PROFILE:-}"
BETA6_GATE_SIGNING_KEY="${BETA6_GATE_SIGNING_KEY:-}"
BETA6_PHASE4_RUNTIME_ENABLED="${BETA6_PHASE4_RUNTIME_ENABLED:-false}"
ENABLE_BETA6_HMM_RUNTIME="${ENABLE_BETA6_HMM_RUNTIME:-false}"
BETA6_RUNTIME_TARGET_COHORT="${BETA6_RUNTIME_TARGET_COHORT:-}"
RETRAIN_INPUT_MODE="${RETRAIN_INPUT_MODE:-auto_aggregate}"
RETRAIN_MANIFEST_PATH="${RETRAIN_MANIFEST_PATH:-}"
export POSTGRES_HOST POSTGRES_PORT POSTGRES_USER POSTGRES_PASSWORD POSTGRES_DB
export ENABLE_BETA6_AUTHORITY RELEASE_GATE_EVIDENCE_PROFILE BETA6_GATE_SIGNING_KEY
export BETA6_PHASE4_RUNTIME_ENABLED ENABLE_BETA6_HMM_RUNTIME BETA6_RUNTIME_TARGET_COHORT
export RETRAIN_INPUT_MODE RETRAIN_MANIFEST_PATH
set_env_key "$BACKEND_DIR/.env" "ENABLE_BETA6_AUTHORITY" "$ENABLE_BETA6_AUTHORITY"
if [ -n "$RELEASE_GATE_EVIDENCE_PROFILE" ]; then
    set_env_key "$BACKEND_DIR/.env" "RELEASE_GATE_EVIDENCE_PROFILE" "$RELEASE_GATE_EVIDENCE_PROFILE"
fi
if [ -n "$BETA6_GATE_SIGNING_KEY" ]; then
    set_env_key "$BACKEND_DIR/.env" "BETA6_GATE_SIGNING_KEY" "$BETA6_GATE_SIGNING_KEY"
fi
set_env_key "$BACKEND_DIR/.env" "RETRAIN_INPUT_MODE" "$RETRAIN_INPUT_MODE"
set_env_key "$BACKEND_DIR/.env" "RETRAIN_MANIFEST_PATH" "$RETRAIN_MANIFEST_PATH"
if ! require_authority_env_contracts; then
    exit 1
fi
if [ "$RETRAIN_INPUT_MODE" = "manifest_only" ] && [ -n "$RETRAIN_MANIFEST_PATH" ] && [ ! -f "$RETRAIN_MANIFEST_PATH" ]; then
    echo "⚠️  RETRAIN_MANIFEST_PATH does not exist: $RETRAIN_MANIFEST_PATH"
    echo "   - Watcher will fallback to auto_aggregate only when incoming files are detected."
fi

# Always sync Web-UI env to the same PostgreSQL values used by Docker/backend.
sync_web_env
echo "   - Synchronized web-ui .env with backend PostgreSQL settings"
echo "   - Beta 6 authority: $ENABLE_BETA6_AUTHORITY"
echo "   - Evidence profile: $RELEASE_GATE_EVIDENCE_PROFILE"
echo "   - Phase4 runtime:  $BETA6_PHASE4_RUNTIME_ENABLED"
echo "   - HMM runtime:     $ENABLE_BETA6_HMM_RUNTIME"
echo "   - Runtime cohort:  ${BETA6_RUNTIME_TARGET_COHORT:-<unset>}"

echo "   - Checking python requirements..."
# pip3 install -r "$BACKEND_DIR/requirements.txt" --quiet

# 3. Start Database Infrastructure (Docker)
echo "🐳 Starting TimescaleDB (PostgreSQL)..."
if ! docker info > /dev/null 2>&1; then
    echo "⚠️  WARNING: Docker is not running."
    if [ "$MODE" = "prod" ]; then
        echo "   - Production mode requires PostgreSQL. Start Docker and re-run."
        exit 1
    fi
    echo "   - Skipping PostgreSQL startup (dev mode)."
    echo "   - If backend is configured with POSTGRES_ONLY=true, the app will fail to start."
else
    POSTGRES_USER="$POSTGRES_USER" POSTGRES_PASSWORD="$POSTGRES_PASSWORD" POSTGRES_DB="$POSTGRES_DB" \
        docker-compose -f "$BACKEND_DIR/docker-compose.yml" up -d
    echo "   - Checking database readiness..."
    if ! POSTGRES_USER="$POSTGRES_USER" POSTGRES_PASSWORD="$POSTGRES_PASSWORD" POSTGRES_DB="$POSTGRES_DB" \
        docker-compose -f "$BACKEND_DIR/docker-compose.yml" up -d --wait; then
        if [ "$MODE" = "prod" ]; then
            echo "❌ PostgreSQL startup timed out in production mode."
            exit 1
        fi
        echo "⚠️  PostgreSQL startup timed out. Continuing in dev mode..."
        echo "   - If backend is configured with POSTGRES_ONLY=true, the app will fail to start."
    fi
    if ! reconcile_postgres_password; then
        exit 1
    fi
fi

# Activate Python 3.12 Virtual Environment
if [ -f "$BACKEND_DIR/venv/bin/activate" ]; then
    echo "🐍 Activating Python 3.12 virtual environment..."
    source "$BACKEND_DIR/venv/bin/activate"
    PYTHON_CMD="$BACKEND_DIR/venv/bin/python"
else
    echo "⚠️  Warning: Virtual environment not found at $BACKEND_DIR/venv"
    echo "   Using system python3 instead"
    PYTHON_CMD="python3"
fi

# 4. Initialize Unified Database (App Layer)
echo "📦 Initializing Unified Database (Beta_6)..."
$PYTHON_CMD "$BACKEND_DIR/scripts/init_db.py"

# 5. Start Backend Automation (Watcher)
echo "👁️  Starting Daily Analysis Watcher..."
$PYTHON_CMD "$BACKEND_DIR/run_daily_analysis.py" &
PID_WATCHER=$!

# 6. Start Streamlit Export Dashboard (Optional but helpful)
if [ ! -f "$STREAMLIT_APP_PATH" ]; then
    echo "⚠️  Streamlit app not found at $STREAMLIT_APP_PATH"
    if [ -f "$LEGACY_STREAMLIT_APP" ]; then
        STREAMLIT_APP_PATH="$LEGACY_STREAMLIT_APP"
        echo "   - Falling back to legacy dashboard: $STREAMLIT_APP_PATH"
    else
        echo "❌ No Streamlit app entrypoint found. Aborting start."
        exit 1
    fi
fi
echo "📊 Starting Streamlit Studio ($STREAMLIT_APP_PATH) on http://localhost:$EXPORT_PORT..."
# Use headless mode and pipe empty input to bypass email prompt
echo "" | streamlit run "$STREAMLIT_APP_PATH" --server.port "$EXPORT_PORT" --server.headless true > "$PROJECT_ROOT/export_ui.log" 2>&1 &
PID_EXPORT=$!

# 7. Start Web UI
echo "🌐 Starting Resident Dashboard on http://localhost:$WEB_PORT..."
(
    cd "$WEB_DIR" || exit 1
    if [ ! -d "node_modules" ]; then
        echo "Installing Web-UI dependencies..."
        npm install > install.log 2>&1
    fi
    if [ "$MODE" = "prod" ]; then
        if ! NODE_ENV=production PORT="$WEB_PORT" npm run build; then
            echo "❌ Web-UI build failed. Production server will not start."
            exit 1
        fi
        if [ ! -d ".next" ]; then
            echo "❌ Build completed but '.next' directory is missing. Aborting production start."
            exit 1
        fi
        NODE_ENV=production PORT="$WEB_PORT" npm run start
    else
        NODE_ENV=development PORT="$WEB_PORT" npm run dev
    fi
) &
PID_WEB=$!

echo "✅ Beta_6 Started!"
echo "   - Access Dashboard: http://localhost:$WEB_PORT"
echo "   - Export Tool:     http://localhost:$EXPORT_PORT"
echo "   - Database:        $DATA_DIR/processed/residents_master_data.db"
echo "   - Retrain Mode:    $RETRAIN_INPUT_MODE"
echo "   - To process new files: Drop into $DATA_DIR/raw (Watcher is active)"
echo "--------------------------------------------------"
echo "Press Ctrl+C to stop."

# Wait for all processes
wait $PID_WEB $PID_WATCHER $PID_EXPORT
