import psycopg2
import os

POSTGRES_CONFIG = {
    'host': os.getenv("POSTGRES_HOST", "localhost"),
    'port': int(os.getenv("POSTGRES_PORT", "5432")),
    'user': os.getenv("POSTGRES_USER", "postgres"),
    'password': os.getenv("POSTGRES_PASSWORD", "password"),
    'dbname': os.getenv("POSTGRES_DB", "elderlycare")
}

TABLES_TO_FIX = [
    "adl_history",
    "activity_segments",
    "alerts",
    "training_history",
    "sleep_analysis" 
]

def fix_identities():
    print("🔧 Fixing PostgreSQL Identity Columns...")
    
    try:
        conn = psycopg2.connect(**POSTGRES_CONFIG)
        cur = conn.cursor()
        
        for table in TABLES_TO_FIX:
            print(f"   Processing {table}...")
            # 1. Create a sequence if not exists (implicit in IDENTITY, but we are altering)
            # Strategy: ADD GENERATED BY DEFAULT AS IDENTITY
            # If it already has one, this might fail, so we wrap in try/except or check.
            
            try:
                # Check directly if it's already an identity column
                cur.execute("""
                    SELECT is_identity 
                    FROM information_schema.columns 
                    WHERE table_name = %s AND column_name = 'id'
                """, (table,))
                res = cur.fetchone()
                
                if res and res[0] == 'YES':
                    print(f"      ✅ {table}.id is already an identity column.")
                    continue

                # Not identity. Add it.
                # First, we need to sync the sequence to the Max ID so we don't collide.
                cur.execute(f"SELECT COALESCE(MAX(id), 0) FROM {table}")
                max_id = cur.fetchone()[0]
                
                print(f"      Current Max ID: {max_id}")
                
                # ALTER TABLE to add identity
                # Note: If it's just INTEGER, we can upgrade it.
                alter_sql = f"ALTER TABLE {table} ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH {max_id + 1});"
                cur.execute(alter_sql)
                print(f"      ✅ Converted {table}.id to GENERATED BY DEFAULT AS IDENTITY")
                
            except Exception as e:
                print(f"      ❌ Failed to fix {table}: {e}")
                conn.rollback()
                continue
            
            conn.commit()
            
        cur.close()
        conn.close()
        print("🎉 All fixes applied.")
        
    except Exception as e:
        print(f"❌ Connection failed: {e}")

if __name__ == "__main__":
    fix_identities()
